// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0urVg0B1niBeToebbNVEIAB3jGwA530s',
    appId: '1:412092994572:web:359d513d21d67097414a29',
    messagingSenderId: '412092994572',
    projectId: 'flutter-chat-93a63',
    authDomain: 'flutter-chat-93a63.firebaseapp.com',
    storageBucket: 'flutter-chat-93a63.firebasestorage.app',
    measurementId: 'G-0YBB7R77XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BKP2h1PdmWezJ1dnDRXb5BxfaV3MPSc',
    appId: '1:412092994572:android:f45dc1dab0c928d3414a29',
    messagingSenderId: '412092994572',
    projectId: 'flutter-chat-93a63',
    storageBucket: 'flutter-chat-93a63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7aZyOM-67aw6gdizw-ZDe9Fyefa9feU',
    appId: '1:412092994572:ios:44a4648c761e002c414a29',
    messagingSenderId: '412092994572',
    projectId: 'flutter-chat-93a63',
    storageBucket: 'flutter-chat-93a63.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7aZyOM-67aw6gdizw-ZDe9Fyefa9feU',
    appId: '1:412092994572:ios:44a4648c761e002c414a29',
    messagingSenderId: '412092994572',
    projectId: 'flutter-chat-93a63',
    storageBucket: 'flutter-chat-93a63.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0urVg0B1niBeToebbNVEIAB3jGwA530s',
    appId: '1:412092994572:web:6fb218774c2f6463414a29',
    messagingSenderId: '412092994572',
    projectId: 'flutter-chat-93a63',
    authDomain: 'flutter-chat-93a63.firebaseapp.com',
    storageBucket: 'flutter-chat-93a63.firebasestorage.app',
    measurementId: 'G-ZDJWDJW72F',
  );
}
